---
exclude: ^deprecated/

default_language_version:
  python: python3.8

repos:
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.27.1
    hooks:
      - id: yamllint
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 732c271
    hooks:
      - id: clang-format
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.37.1
    hooks:
      - id: pyupgrade
        args: [--py38-plus]
  - repo: https://github.com/tier4/pre-commit-hooks-ros
    rev: v0.7.0
    hooks:
      - id: prettier-xacro
      - id: prettier-launch-xml
      - id: prettier-package-xml
      - id: sort-package-xml
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-symlinks
      - id: check-json
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: no-commit-to-branch
        args:
          - --branch=master
