# /home/andrespulido/.config/tmuxinator/visualization.yml

name: visualization
root: ~/mml_ws

windows:
  - guidance_viz:
      layout: even-vertical 
      panes:
        - topic_check: 
          - source install/setup.bash && cd src/mml_guidance
        - roslaunch:
          - source install/setup.bash && cd src/mml_guidance
        - sim_helper:
          - source install/setup.bash && ros2 launch isaacsim run_isaacsim.launch.py gui:=//home/andres/mml_ws/src/mml_guidance/simulation/isaac_mml_env.usd play_sim_on_start:=true

